[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[functions]]
  path = "/netlify/functions/login"
  [functions.login]
    timeout = 10

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
